### ISSUE TITLE
Fifo and Lifo queue

### ISSUE THREAD

**Issue by JulienDev** [vinaysshenoy/enhanced-volley#1]
Hi,

It would be nice if we could set the queue type, Fifo or Lifo for example.

Julien

**Comment by vinaysshenoy** [comment]
The current queue implementation(PriorityBlockingQueue) is probably the best queue type for network requests. Is there a particular use case where a LIFO queue is needed?

**Comment by JulienDev** [comment]
Thank you for your answer ! The use case is the following. I need to make requests each time a ScrollView is stopped. If I scroll and stop the list few times in a row it takes a long time to start the last added request and then it takes a long time to show the result in the cell.

**Comment by vinaysshenoy** [comment]
A Queue is generally FIFO and I'm reluctant to break queue semantics for this reason.

Instead of changing the queue, won't a better option be to not add any requests to the queue for about 200 ms until AFTER the ScrollView has stopped scrolling? That would be the more optimal solution.

You can also use [Request#setPriority()](https://github.com/vinaysshenoy/enhanced-volley/blob/master/src/com/android/volley/Request.java#L467) with a priority of [IMMEDIATE](https://github.com/vinaysshenoy/enhanced-volley/blob/master/src/com/android/volley/Request.java#L459) to add a particular request to the front of queue. Let me know if this works out for you, otherwise we'll figure out a way to solve it.
